apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: fission
    meta.helm.sh/release-namespace: fission
  creationTimestamp: "2024-04-26T01:49:30Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: fission-all-v1.20.0
    svc: buildermgr
  name: buildermgr
  namespace: fission
  resourceVersion: "111178"
  uid: bfe8fc4b-399f-4fa5-aa7c-ecf7a204e9df
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      svc: buildermgr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        svc: buildermgr
    spec:
      containers:
      - args:
        - --builderMgr
        - --storageSvcUrl
        - http://storagesvc.fission
        command:
        - /fission-bundle
        env:
        - name: FETCHER_IMAGE
          value: fission/fetcher:v1.20.0
        - name: FETCHER_IMAGE_PULL_POLICY
          value: IfNotPresent
        - name: BUILDER_IMAGE_PULL_POLICY
          value: IfNotPresent
        - name: ENABLE_ISTIO
          value: "false"
        - name: FETCHER_MINCPU
          value: 10m
        - name: FETCHER_MINMEM
          value: 16Mi
        - name: FETCHER_MAXCPU
        - name: FETCHER_MAXMEM
        - name: DEBUG_ENV
          value: "false"
        - name: PPROF_ENABLED
          value: "false"
        - name: HELM_RELEASE_NAME
          value: fission
        - name: FISSION_BUILDER_NAMESPACE
        - name: FISSION_FUNCTION_NAMESPACE
        - name: FISSION_DEFAULT_NAMESPACE
          value: default
        - name: FISSION_RESOURCE_NAMESPACES
          value: default
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_TRACES_SAMPLER
          value: parentbased_traceidratio
        - name: OTEL_TRACES_SAMPLER_ARG
          value: "0.1"
        - name: OTEL_PROPAGATORS
          value: tracecontext,baggage
        image: ghcr.io/fission/fission-bundle:v1.20.0
        imagePullPolicy: IfNotPresent
        name: buildermgr
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      serviceAccount: fission-buildermgr
      serviceAccountName: fission-buildermgr
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-04-26T01:49:43Z"
    lastUpdateTime: "2024-04-26T01:49:43Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-04-26T01:49:30Z"
    lastUpdateTime: "2024-04-26T01:49:43Z"
    message: ReplicaSet "buildermgr-b9d6b56f9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
