apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: fission
    meta.helm.sh/release-namespace: fission
  creationTimestamp: "2024-04-26T01:49:30Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: fission-all-v1.20.0
    messagequeue: keda
    svc: mqtrigger-keda
  name: mqtrigger-keda
  namespace: fission
  resourceVersion: "111175"
  uid: 13f5279b-3f63-49ed-b99e-ac1011871dd5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      messagequeue: keda
      svc: mqtrigger-keda
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        messagequeue: keda
        svc: mqtrigger-keda
    spec:
      containers:
      - args:
        - --mqt_keda
        - --routerUrl
        - http://router.fission
        command:
        - /fission-bundle
        env:
        - name: DEBUG_ENV
          value: "false"
        - name: CONNECTOR_IMAGE_PULL_POLICY
          value: IfNotPresent
        - name: KAFKA_IMAGE
          value: ghcr.io/fission/keda-kafka-http-connector:v0.13
        - name: RABBITMQ_IMAGE
          value: ghcr.io/fission/keda-rabbitmq-http-connector:v0.11
        - name: AWS-KINESIS-STREAM_IMAGE
          value: ghcr.io/fission/keda-aws-kinesis-http-connector:v0.11
        - name: AWS-SQS-QUEUE_IMAGE
          value: ghcr.io/fission/keda-aws-sqs-http-connector:v0.12
        - name: STAN_IMAGE
          value: ghcr.io/fission/keda-nats-streaming-http-connector:v0.14
        - name: NATS-JETSTREAM_IMAGE
          value: ghcr.io/fission/keda-nats-jetstream-http-connector:v0.5
        - name: GCP-PUBSUB_IMAGE
          value: ghcr.io/fission/keda-gcp-pubsub-http-connector:v0.7
        - name: REDIS_IMAGE
          value: ghcr.io/fission/keda-redis-http-connector:v0.4
        - name: FISSION_BUILDER_NAMESPACE
        - name: FISSION_FUNCTION_NAMESPACE
        - name: FISSION_DEFAULT_NAMESPACE
          value: default
        - name: FISSION_RESOURCE_NAMESPACES
          value: default
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_TRACES_SAMPLER
          value: parentbased_traceidratio
        - name: OTEL_TRACES_SAMPLER_ARG
          value: "0.1"
        - name: OTEL_PROPAGATORS
          value: tracecontext,baggage
        image: ghcr.io/fission/fission-bundle:v1.20.0
        imagePullPolicy: IfNotPresent
        name: mqtrigger-keda
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: fission-keda
      serviceAccountName: fission-keda
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-04-26T01:49:43Z"
    lastUpdateTime: "2024-04-26T01:49:43Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-04-26T01:49:30Z"
    lastUpdateTime: "2024-04-26T01:49:43Z"
    message: ReplicaSet "mqtrigger-keda-7c8b8f5ddc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
