apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: fission
    meta.helm.sh/release-namespace: fission
  creationTimestamp: "2024-04-26T01:49:30Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    application: fission-router
    chart: fission-all-v1.20.0
    svc: router
  name: router
  namespace: fission
  resourceVersion: "111252"
  uid: 8bca556a-c26e-4115-bb71-c8edc8a1b11c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      application: fission-router
      svc: router
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        application: fission-router
        svc: router
    spec:
      containers:
      - args:
        - --routerPort
        - "8888"
        - --executorUrl
        - http://executor.fission
        command:
        - /fission-bundle
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: ROUTER_ROUND_TRIP_TIMEOUT
          value: 50ms
        - name: ROUTER_ROUNDTRIP_TIMEOUT_EXPONENT
          value: "2"
        - name: ROUTER_ROUND_TRIP_KEEP_ALIVE_TIME
          value: 30s
        - name: ROUTER_ROUND_TRIP_DISABLE_KEEP_ALIVE
          value: "true"
        - name: ROUTER_ROUND_TRIP_MAX_RETRIES
          value: "10"
        - name: ROUTER_SVC_ADDRESS_MAX_RETRIES
          value: "5"
        - name: ROUTER_SVC_ADDRESS_UPDATE_TIMEOUT
          value: 30s
        - name: ROUTER_UNTAP_SERVICE_TIMEOUT
          value: 3600s
        - name: USE_ENCODED_PATH
          value: "false"
        - name: DEBUG_ENV
          value: "false"
        - name: PPROF_ENABLED
          value: "false"
        - name: DISPLAY_ACCESS_LOG
          value: "false"
        - name: FISSION_BUILDER_NAMESPACE
        - name: FISSION_FUNCTION_NAMESPACE
        - name: FISSION_DEFAULT_NAMESPACE
          value: default
        - name: FISSION_RESOURCE_NAMESPACES
          value: default
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_TRACES_SAMPLER
          value: parentbased_traceidratio
        - name: OTEL_TRACES_SAMPLER_ARG
          value: "0.1"
        - name: OTEL_PROPAGATORS
          value: tracecontext,baggage
        image: ghcr.io/fission/fission-bundle:v1.20.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /router-healthz
            port: 8888
            scheme: HTTP
          initialDelaySeconds: 35
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: router
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8888
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /router-healthz
            port: 8888
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/config/config.yaml
          name: config-volume
          subPath: config.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      serviceAccount: fission-router
      serviceAccountName: fission-router
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: feature-config
        name: config-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-04-26T01:49:51Z"
    lastUpdateTime: "2024-04-26T01:49:51Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-04-26T01:49:30Z"
    lastUpdateTime: "2024-04-26T01:49:51Z"
    message: ReplicaSet "router-747967986f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
