apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: fission
    meta.helm.sh/release-namespace: fission
  creationTimestamp: "2024-04-26T01:49:30Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    application: fission-storage
    chart: fission-all-v1.20.0
    svc: storagesvc
  name: storagesvc
  namespace: fission
  resourceVersion: "111219"
  uid: 76371f38-d364-40ae-b4f9-301148fb6167
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      application: fission-storage
      svc: storagesvc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        application: fission-storage
        svc: storagesvc
    spec:
      containers:
      - args:
        - --storageServicePort
        - "8000"
        - --storageType
        - local
        command:
        - /fission-bundle
        env:
        - name: PRUNE_ENABLED
          value: "true"
        - name: PRUNE_INTERVAL
          value: "60"
        - name: DEBUG_ENV
          value: "false"
        - name: PPROF_ENABLED
          value: "false"
        - name: FISSION_BUILDER_NAMESPACE
        - name: FISSION_FUNCTION_NAMESPACE
        - name: FISSION_DEFAULT_NAMESPACE
          value: default
        - name: FISSION_RESOURCE_NAMESPACES
          value: default
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_TRACES_SAMPLER
          value: parentbased_traceidratio
        - name: OTEL_TRACES_SAMPLER_ARG
          value: "0.1"
        - name: OTEL_PROPAGATORS
          value: tracecontext,baggage
        image: ghcr.io/fission/fission-bundle:v1.20.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 35
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: storagesvc
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /fission
          name: fission-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      serviceAccount: fission-storagesvc
      serviceAccountName: fission-storagesvc
      terminationGracePeriodSeconds: 30
      volumes:
      - name: fission-storage
        persistentVolumeClaim:
          claimName: fission-storage-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-04-26T01:49:47Z"
    lastUpdateTime: "2024-04-26T01:49:47Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-04-26T01:49:30Z"
    lastUpdateTime: "2024-04-26T01:49:47Z"
    message: ReplicaSet "storagesvc-5d98cd6f54" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
