apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: fission
    meta.helm.sh/release-namespace: fission
  creationTimestamp: "2024-04-26T01:49:30Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: fission-all-v1.20.0
    svc: timer
  name: timer
  namespace: fission
  resourceVersion: "111239"
  uid: 3b6a831d-2cc1-493f-9a79-f955457e1728
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      svc: timer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        svc: timer
    spec:
      containers:
      - args:
        - --timer
        - --routerUrl
        - http://router.fission
        command:
        - /fission-bundle
        env:
        - name: DEBUG_ENV
          value: "false"
        - name: PPROF_ENABLED
          value: "false"
        - name: FISSION_BUILDER_NAMESPACE
        - name: FISSION_FUNCTION_NAMESPACE
        - name: FISSION_DEFAULT_NAMESPACE
          value: default
        - name: FISSION_RESOURCE_NAMESPACES
          value: default
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_TRACES_SAMPLER
          value: parentbased_traceidratio
        - name: OTEL_TRACES_SAMPLER_ARG
          value: "0.1"
        - name: OTEL_PROPAGATORS
          value: tracecontext,baggage
        image: ghcr.io/fission/fission-bundle:v1.20.0
        imagePullPolicy: IfNotPresent
        name: timer
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      serviceAccount: fission-timer
      serviceAccountName: fission-timer
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-04-26T01:49:50Z"
    lastUpdateTime: "2024-04-26T01:49:50Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-04-26T01:49:30Z"
    lastUpdateTime: "2024-04-26T01:49:50Z"
    message: ReplicaSet "timer-66c797b5c6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
