apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: fission
    meta.helm.sh/release-namespace: fission
  creationTimestamp: "2024-04-26T01:49:30Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    application: fission-webhook
    chart: fission-all-v1.20.0
    svc: webhook-service
  name: webhook
  namespace: fission
  resourceVersion: "111163"
  uid: fcbea110-7174-47fb-818d-b77e48fa2f92
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      application: fission-webhook
      svc: webhook-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        application: fission-webhook
        svc: webhook-service
    spec:
      containers:
      - args:
        - --webhookPort
        - "9443"
        command:
        - /fission-bundle
        image: ghcr.io/fission/fission-bundle:v1.20.0
        imagePullPolicy: IfNotPresent
        name: webhook
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: serving-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      serviceAccount: fission-webhook
      serviceAccountName: fission-webhook
      terminationGracePeriodSeconds: 30
      volumes:
      - name: serving-certs
        secret:
          defaultMode: 420
          secretName: fission-webhook-certs
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-04-26T01:49:42Z"
    lastUpdateTime: "2024-04-26T01:49:42Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-04-26T01:49:30Z"
    lastUpdateTime: "2024-04-26T01:49:42Z"
    message: ReplicaSet "webhook-7bb6d4875b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
