apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: auth
type: Opaque
data:
  ES_USERNAME: ZWxhc3RpYw==     # 'elastic' Enconded Base64
  ES_PASSWORD: ZWxhc3RpYw==     # 'elastic' Enconded Base64
  EPA_APIKEY: N2QzYzk5MDFlNDc1NDAyZjg0NDY5MWMzMDBlNGVmYTg=  # '7d3c9901e475402f844691c300e4efa8' Enconded Base64