include:
- ./functions/putCOPD/put-COPD.zip
kind: ArchiveUploadSpec
name: functions-putcopd-put-copd-zip-bjMg

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: put-COPD
  namespace: default
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://functions-putcopd-put-copd-zip-bjMg
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-20T07:09:03Z"
