include:
- ./functions/putHousePrice/put-houseprice.zip
kind: ArchiveUploadSpec
name: functions-puthouseprice-put-houseprice-zip-7W5p

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: put-houseprice
  namespace: default
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://functions-puthouseprice-put-houseprice-zip-7W5p
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-20T07:09:04Z"
