include:
- ./functions/get_houseprice_copd/get-houseprice-copd.zip
kind: ArchiveUploadSpec
name: functions-get-houseprice-copd-get-houseprice-copd-zip-UdIs

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-houseprice-copd
  namespace: default
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://functions-get-houseprice-copd-get-houseprice-copd-zip-UdIs
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-20T07:09:02Z"
