include:
- ./functions/updateEpaAllAirQualityMonitorSitesData/update-airquality.zip
kind: ArchiveUploadSpec
name: functions-updateepaallairqualitymonitorsitesdata-update-airqual-MEse

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: update-airquality
  namespace: default
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://functions-updateepaallairqualitymonitorsitesdata-update-airqual-MEse
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-20T07:09:07Z"
