include:
- ./functions/putVehicle/put-vehicle.zip
kind: ArchiveUploadSpec
name: functions-putvehicle-put-vehicle-zip-A7XQ

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: put-vehicle
  namespace: default
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://functions-putvehicle-put-vehicle-zip-A7XQ
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-20T07:09:05Z"
