include:
- ./functions/get_airquality_vehicles/get-airquality-vehicle.zip
kind: ArchiveUploadSpec
name: functions-get-airquality-vehicles-get-airquality-vehicle-zip-SMci

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-airquality-vehicle
  namespace: default
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://functions-get-airquality-vehicles-get-airquality-vehicle-zip-SMci
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-20T07:09:01Z"
