include:
- ./functions/post_json_data_from_local/upload.zip
kind: ArchiveUploadSpec
name: functions-post-json-data-from-local-upload-zip-iAEg

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: post-json-data-from-local
  namespace: default
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://functions-post-json-data-from-local-upload-zip-iAEg
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-21T04:56:10Z"
