apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: update-airquality
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: update-airquality
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /update-airquality
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /update-airquality
