apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: put-houseprice
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: put-houseprice
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /put-houseprice
    tls: ""
  method: ""
  methods:
  - PUT
  prefix: ""
  relativeurl: /put-houseprice
