apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: airquality-rsd
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: get-airquality-rsd
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /airquality/rsd
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /airquality/rsd
