apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: post-json-data-from-local
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: post-json-data-from-local
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /post-json-data-from-local/{index}
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /post-json-data-from-local/{index}
