apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: houseprice-copd
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: get-houseprice-copd
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /houseprice/copd
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /houseprice/copd
