apiVersion: v1
kind: Pod
metadata:
  annotations:
    executorInstanceId: leb4nndk
  creationTimestamp: "2024-05-09T06:16:15Z"
  generateName: poolmgr-python-default-3305617-cb9846bcc-
  labels:
    environmentName: python
    environmentNamespace: default
    environmentUid: cd9dafa1-3601-4f90-8845-4aed92bf4436
    executorType: poolmgr
    functionName: helloworld
    functionNamespace: default
    functionUid: 1c9b6201-b50d-4ce7-8b03-e346f5e1c358
    managed: "false"
    pod-template-hash: cb9846bcc
  name: poolmgr-python-default-3305617-cb9846bcc-lxqzk
  namespace: default
  resourceVersion: "3512145"
  uid: caa0f3d2-9ced-4fe4-b39a-25b7e78851b8
spec:
  containers:
  - image: fission/python-env-3.9
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sleep
          - "0"
    name: python
    ports:
    - containerPort: 8000
      name: http-fetcher
      protocol: TCP
    - containerPort: 8888
      name: http-env
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /userfunc
      name: userfunc
    - mountPath: /secrets
      name: secrets
    - mountPath: /configs
      name: configmaps
    - mountPath: /etc/podinfo
      name: podinfo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-lffx9
      readOnly: true
  - command:
    - /fetcher
    - -secret-dir
    - /secrets
    - -cfgmap-dir
    - /configs
    - /userfunc
    env:
    - name: OTEL_PROPAGATORS
      value: tracecontext,baggage
    - name: OTEL_TRACES_SAMPLER
      value: parentbased_traceidratio
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
    - name: OTEL_EXPORTER_OTLP_INSECURE
      value: "true"
    - name: OTEL_TRACES_SAMPLER_ARG
      value: "0.1"
    image: fission/fetcher:v1.20.0
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sleep
          - "0"
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8000
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    name: fetcher
    readinessProbe:
      failureThreshold: 30
      httpGet:
        path: /readiness-healthz
        port: 8000
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 1
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /userfunc
      name: userfunc
    - mountPath: /secrets
      name: secrets
    - mountPath: /configs
      name: configmaps
    - mountPath: /etc/podinfo
      name: podinfo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-lffx9
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: elastic-g3wcd274rwob-node-0
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: fission-fetcher
  serviceAccountName: fission-fetcher
  terminationGracePeriodSeconds: 0
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: userfunc
  - emptyDir: {}
    name: secrets
  - emptyDir: {}
    name: configmaps
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
        path: name
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
        path: namespace
    name: podinfo
  - name: kube-api-access-lffx9
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-05-09T06:16:15Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-05-09T06:16:23Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-05-09T06:16:23Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-05-09T06:16:15Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://a518806dc424c92cace5d3cc0f7bc4dda8c86e3fa446894741c4a3a01c385522
    image: docker.io/fission/fetcher:v1.20.0
    imageID: docker.io/fission/fetcher@sha256:9d99de3e502540bcc0ee6573ce48171fa2bfaeeaf4200d37b383349ec7fde7a4
    lastState: {}
    name: fetcher
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-05-09T06:16:22Z"
  - containerID: containerd://baa10ed19813b5d8afbfa4f15b6f1729f0da359cea185ceb052cca4cf7571468
    image: docker.io/fission/python-env-3.9:latest
    imageID: docker.io/fission/python-env-3.9@sha256:44c9f6afbc6b3257dcf980d6a0c729e0ac90c2a751936e4d6cb9535f283d5b1b
    lastState: {}
    name: python
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-05-09T06:16:19Z"
  hostIP: 192.168.10.60
  phase: Running
  podIP: 10.100.1.72
  podIPs:
  - ip: 10.100.1.72
  qosClass: Burstable
  startTime: "2024-05-09T06:16:15Z"
