apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-05-10T06:21:00Z"
  generateName: poolmgr-nodejs-default-3305577-64d79bf5bd-
  labels:
    environmentName: nodejs
    environmentNamespace: default
    environmentUid: 47069a70-d965-4074-90dd-17ec23ff2994
    executorType: poolmgr
    managed: "true"
    pod-template-hash: 64d79bf5bd
  name: poolmgr-nodejs-default-3305577-64d79bf5bd-x6l78
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: poolmgr-nodejs-default-3305577-64d79bf5bd
    uid: e46151fc-fd7a-48ee-b77a-0a1c741b8289
  resourceVersion: "3560270"
  uid: 9f055cfa-e9bf-4b94-ba17-df9c60021211
spec:
  containers:
  - image: fission/node-env
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sleep
          - "0"
    name: nodejs
    ports:
    - containerPort: 8000
      name: http-fetcher
      protocol: TCP
    - containerPort: 8888
      name: http-env
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /userfunc
      name: userfunc
    - mountPath: /secrets
      name: secrets
    - mountPath: /configs
      name: configmaps
    - mountPath: /etc/podinfo
      name: podinfo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-dq2f8
      readOnly: true
  - command:
    - /fetcher
    - -secret-dir
    - /secrets
    - -cfgmap-dir
    - /configs
    - /userfunc
    env:
    - name: OTEL_PROPAGATORS
      value: tracecontext,baggage
    - name: OTEL_TRACES_SAMPLER
      value: parentbased_traceidratio
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
    - name: OTEL_EXPORTER_OTLP_INSECURE
      value: "true"
    - name: OTEL_TRACES_SAMPLER_ARG
      value: "0.1"
    image: fission/fetcher:v1.20.0
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sleep
          - "0"
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8000
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    name: fetcher
    readinessProbe:
      failureThreshold: 30
      httpGet:
        path: /readiness-healthz
        port: 8000
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 1
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /userfunc
      name: userfunc
    - mountPath: /secrets
      name: secrets
    - mountPath: /configs
      name: configmaps
    - mountPath: /etc/podinfo
      name: podinfo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-dq2f8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: elastic-g3wcd274rwob-node-0
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: fission-fetcher
  serviceAccountName: fission-fetcher
  terminationGracePeriodSeconds: 0
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: userfunc
  - emptyDir: {}
    name: secrets
  - emptyDir: {}
    name: configmaps
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
        path: name
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
        path: namespace
    name: podinfo
  - name: kube-api-access-dq2f8
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-05-10T06:21:00Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-05-10T06:21:07Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-05-10T06:21:07Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-05-10T06:21:00Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://dfe95188bfb4640038738896b9340514e0e210b430ef6413dd57dfe28254c249
    image: docker.io/fission/fetcher:v1.20.0
    imageID: docker.io/fission/fetcher@sha256:9d99de3e502540bcc0ee6573ce48171fa2bfaeeaf4200d37b383349ec7fde7a4
    lastState: {}
    name: fetcher
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-05-10T06:21:06Z"
  - containerID: containerd://891fec9f90608b0a21fdb864eedf577463c43ab06923d0c8e4a423f3a7dd1057
    image: docker.io/fission/node-env:latest
    imageID: docker.io/fission/node-env@sha256:90d36e0b4714d515e69028faae26b3b9a3f98b6e0fd1d8acea35deda44265480
    lastState: {}
    name: nodejs
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-05-10T06:21:03Z"
  hostIP: 192.168.10.60
  phase: Running
  podIP: 10.100.1.92
  podIPs:
  - ip: 10.100.1.92
  qosClass: Burstable
  startTime: "2024-05-10T06:21:00Z"
