apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    executorInstanceId: leb4nndk
  creationTimestamp: "2024-05-16T05:57:22Z"
  generation: 1
  labels:
    environmentName: java
    environmentNamespace: default
    environmentUid: 7c09c11d-b64b-41ef-97a7-12f50b1d932c
    executorType: poolmgr
    managed: "true"
  name: poolmgr-java-default-4895505
  namespace: default
  resourceVersion: "4911008"
  uid: bf865cbb-bd75-427a-9ba3-508b7eb79119
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      environmentName: java
      environmentNamespace: default
      environmentUid: 7c09c11d-b64b-41ef-97a7-12f50b1d932c
      executorType: poolmgr
      managed: "true"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        environmentName: java
        environmentNamespace: default
        environmentUid: 7c09c11d-b64b-41ef-97a7-12f50b1d932c
        executorType: poolmgr
        managed: "true"
    spec:
      containers:
      - image: fission/jvm-env
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sleep
              - "0"
        name: java
        ports:
        - containerPort: 8000
          name: http-fetcher
          protocol: TCP
        - containerPort: 8888
          name: http-env
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /userfunc
          name: userfunc
        - mountPath: /secrets
          name: secrets
        - mountPath: /configs
          name: configmaps
        - mountPath: /etc/podinfo
          name: podinfo
      - command:
        - /fetcher
        - -secret-dir
        - /secrets
        - -cfgmap-dir
        - /configs
        - /userfunc
        env:
        - name: OTEL_PROPAGATORS
          value: tracecontext,baggage
        - name: OTEL_TRACES_SAMPLER
          value: parentbased_traceidratio
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_TRACES_SAMPLER_ARG
          value: "0.1"
        image: fission/fetcher:v1.20.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sleep
              - "0"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: fetcher
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /readiness-healthz
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /userfunc
          name: userfunc
        - mountPath: /secrets
          name: secrets
        - mountPath: /configs
          name: configmaps
        - mountPath: /etc/podinfo
          name: podinfo
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: fission-fetcher
      serviceAccountName: fission-fetcher
      terminationGracePeriodSeconds: 0
      volumes:
      - emptyDir: {}
        name: userfunc
      - emptyDir: {}
        name: secrets
      - emptyDir: {}
        name: configmaps
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
            path: name
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
        name: podinfo
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2024-05-16T05:57:22Z"
    lastUpdateTime: "2024-05-16T05:57:33Z"
    message: ReplicaSet "poolmgr-java-default-4895505-9ccbd694" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-05-16T07:32:55Z"
    lastUpdateTime: "2024-05-16T07:32:55Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
