apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    executorInstanceId: leb4nndk
  creationTimestamp: "2024-05-09T04:44:07Z"
  generation: 1
  labels:
    environmentName: nodejs
    environmentNamespace: default
    environmentUid: 47069a70-d965-4074-90dd-17ec23ff2994
    executorType: poolmgr
    managed: "true"
  name: poolmgr-nodejs-default-3305577
  namespace: default
  resourceVersion: "4892874"
  uid: d96a31a6-9a14-4e08-ab7c-7c3ee698c1ad
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      environmentName: nodejs
      environmentNamespace: default
      environmentUid: 47069a70-d965-4074-90dd-17ec23ff2994
      executorType: poolmgr
      managed: "true"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        environmentName: nodejs
        environmentNamespace: default
        environmentUid: 47069a70-d965-4074-90dd-17ec23ff2994
        executorType: poolmgr
        managed: "true"
    spec:
      containers:
      - image: fission/node-env
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sleep
              - "0"
        name: nodejs
        ports:
        - containerPort: 8000
          name: http-fetcher
          protocol: TCP
        - containerPort: 8888
          name: http-env
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /userfunc
          name: userfunc
        - mountPath: /secrets
          name: secrets
        - mountPath: /configs
          name: configmaps
        - mountPath: /etc/podinfo
          name: podinfo
      - command:
        - /fetcher
        - -secret-dir
        - /secrets
        - -cfgmap-dir
        - /configs
        - /userfunc
        env:
        - name: OTEL_PROPAGATORS
          value: tracecontext,baggage
        - name: OTEL_TRACES_SAMPLER
          value: parentbased_traceidratio
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_TRACES_SAMPLER_ARG
          value: "0.1"
        image: fission/fetcher:v1.20.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sleep
              - "0"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: fetcher
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /readiness-healthz
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /userfunc
          name: userfunc
        - mountPath: /secrets
          name: secrets
        - mountPath: /configs
          name: configmaps
        - mountPath: /etc/podinfo
          name: podinfo
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: fission-fetcher
      serviceAccountName: fission-fetcher
      terminationGracePeriodSeconds: 0
      volumes:
      - emptyDir: {}
        name: userfunc
      - emptyDir: {}
        name: secrets
      - emptyDir: {}
        name: configmaps
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
            path: name
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
        name: podinfo
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2024-05-09T04:44:07Z"
    lastUpdateTime: "2024-05-09T04:44:22Z"
    message: ReplicaSet "poolmgr-nodejs-default-3305577-64d79bf5bd" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-05-16T05:42:31Z"
    lastUpdateTime: "2024-05-16T05:42:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
