apiVersion: v1
data:
  password: ZWxhc3RpYw==
  username: ZWxhc3RpYw==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: elasticsearch
    meta.helm.sh/release-namespace: elastic
  creationTimestamp: "2024-04-26T01:18:01Z"
  labels:
    app: elasticsearch-master
    app.kubernetes.io/managed-by: Helm
    chart: elasticsearch
    heritage: Helm
    release: elasticsearch
  name: elasticsearch-master-credentials
  namespace: elastic
  resourceVersion: "105148"
  uid: 32767d50-5d61-40cf-9e87-68dee5dea5de
type: Opaque
