apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-09T04:44:08Z"
  labels:
    envName: python
    envNamespace: default
    envResourceVersion: "3305617"
    owner: buildermgr
  name: python-3305617
  namespace: default
  resourceVersion: "3305623"
  uid: 3d1ca4a3-b81c-4a7b-821e-e34678924420
spec:
  clusterIP: 10.254.191.8
  clusterIPs:
  - 10.254.191.8
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: fetcher-port
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: builder-port
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    envName: python
    envNamespace: default
    envResourceVersion: "3305617"
    owner: buildermgr
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
