apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: cinder.csi.openstack.org
    volume.kubernetes.io/storage-provisioner: cinder.csi.openstack.org
  creationTimestamp: "2024-04-26T01:18:01Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: elasticsearch-master
  name: elasticsearch-master-elasticsearch-master-1
  namespace: elastic
  resourceVersion: "105206"
  uid: eb580f81-9b78-4457-a772-5c5d31e5d8b4
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: default
  volumeMode: Filesystem
  volumeName: pvc-eb580f81-9b78-4457-a772-5c5d31e5d8b4
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  phase: Bound
