apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/job-tracking: ""
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "1"
  creationTimestamp: "2024-05-10T04:38:18Z"
  generation: 1
  labels:
    app: fission-all
    chart: fission-all-v1.20.0
    release: fission
  name: fission-fission-all-v1.20.0-818
  namespace: fission
  resourceVersion: "3542686"
  uid: 369b0606-6af6-42b5-b828-b910a524eb45
spec:
  backoffLimit: 0
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 369b0606-6af6-42b5-b828-b910a524eb45
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fission-all
        controller-uid: 369b0606-6af6-42b5-b828-b910a524eb45
        job-name: fission-fission-all-v1.20.0-818
        release: fission
      name: fission-fission-all
    spec:
      containers:
      - command:
        - /pre-upgrade-checks
        env:
        - name: FISSION_BUILDER_NAMESPACE
        - name: FISSION_FUNCTION_NAMESPACE
        - name: FISSION_DEFAULT_NAMESPACE
          value: default
        - name: FISSION_RESOURCE_NAMESPACES
          value: default
        image: fission/pre-upgrade-checks:v1.20.0
        imagePullPolicy: IfNotPresent
        name: pre-upgrade-job
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: fission-preupgrade
      serviceAccountName: fission-preupgrade
      terminationGracePeriodSeconds: 30
status:
  completionTime: "2024-05-10T04:38:41Z"
  conditions:
  - lastProbeTime: "2024-05-10T04:38:41Z"
    lastTransitionTime: "2024-05-10T04:38:41Z"
    status: "True"
    type: Complete
  ready: 0
  startTime: "2024-05-10T04:38:18Z"
  succeeded: 1
  uncountedTerminatedPods: {}
