apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: fission
    meta.helm.sh/release-namespace: fission
  creationTimestamp: "2024-04-26T01:49:29Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    application: fission-router
    chart: fission-all-v1.20.0
    svc: router
  name: router
  namespace: fission
  resourceVersion: "110980"
  uid: ef6e372c-d760-4647-94f0-05f78ce60dcd
spec:
  clusterIP: 10.254.107.213
  clusterIPs:
  - 10.254.107.213
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    svc: router
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
