apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: fission
    meta.helm.sh/release-namespace: fission
  creationTimestamp: "2024-04-26T01:49:29Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    application: fission-storage
    chart: fission-all-v1.20.0
    svc: storagesvc
  name: storagesvc
  namespace: fission
  resourceVersion: "110972"
  uid: 1bda9760-3d72-49b6-af7c-91e6b8fee530
spec:
  clusterIP: 10.254.69.78
  clusterIPs:
  - 10.254.69.78
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    svc: storagesvc
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
