apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: fission
    meta.helm.sh/release-namespace: fission
  creationTimestamp: "2024-04-26T01:49:29Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    application: fission-webhook
    chart: fission-all-v1.20.0
    svc: webhook-service
  name: webhook-service
  namespace: fission
  resourceVersion: "110977"
  uid: 3f8391f0-fe7c-4d00-bf5c-48a1f3580cbe
spec:
  clusterIP: 10.254.185.201
  clusterIPs:
  - 10.254.185.201
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    svc: webhook-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
