apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  creationTimestamp: "2024-04-26T01:49:30Z"
  generateName: buildermgr-b9d6b56f9-
  labels:
    pod-template-hash: b9d6b56f9
    svc: buildermgr
  name: buildermgr-b9d6b56f9-vndnp
  namespace: fission
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: buildermgr-b9d6b56f9
    uid: a3fcdeb1-67ee-4423-98a2-92c463e3a296
  resourceVersion: "111176"
  uid: 8b40e576-7658-4900-98c9-448474d658b9
spec:
  containers:
  - args:
    - --builderMgr
    - --storageSvcUrl
    - http://storagesvc.fission
    command:
    - /fission-bundle
    env:
    - name: FETCHER_IMAGE
      value: fission/fetcher:v1.20.0
    - name: FETCHER_IMAGE_PULL_POLICY
      value: IfNotPresent
    - name: BUILDER_IMAGE_PULL_POLICY
      value: IfNotPresent
    - name: ENABLE_ISTIO
      value: "false"
    - name: FETCHER_MINCPU
      value: 10m
    - name: FETCHER_MINMEM
      value: 16Mi
    - name: FETCHER_MAXCPU
    - name: FETCHER_MAXMEM
    - name: DEBUG_ENV
      value: "false"
    - name: PPROF_ENABLED
      value: "false"
    - name: HELM_RELEASE_NAME
      value: fission
    - name: FISSION_BUILDER_NAMESPACE
    - name: FISSION_FUNCTION_NAMESPACE
    - name: FISSION_DEFAULT_NAMESPACE
      value: default
    - name: FISSION_RESOURCE_NAMESPACES
      value: default
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
    - name: OTEL_EXPORTER_OTLP_INSECURE
      value: "true"
    - name: OTEL_TRACES_SAMPLER
      value: parentbased_traceidratio
    - name: OTEL_TRACES_SAMPLER_ARG
      value: "0.1"
    - name: OTEL_PROPAGATORS
      value: tracecontext,baggage
    image: ghcr.io/fission/fission-bundle:v1.20.0
    imagePullPolicy: IfNotPresent
    name: buildermgr
    ports:
    - containerPort: 8080
      name: metrics
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-xczj8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: elastic-g3wcd274rwob-node-0
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001
  serviceAccount: fission-buildermgr
  serviceAccountName: fission-buildermgr
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-xczj8
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-04-26T01:49:30Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-04-26T01:49:42Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-04-26T01:49:42Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-04-26T01:49:30Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://912ff8284f3bfddb833cf5e9d9ff6395a6a3294fd7edc44ecd3ecde1d7307f6e
    image: ghcr.io/fission/fission-bundle:v1.20.0
    imageID: ghcr.io/fission/fission-bundle@sha256:53bfa3f9c7ea3beb3c51775372a1ab5aa43e58a88c6fde155d0cf58663cc82bd
    lastState: {}
    name: buildermgr
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-04-26T01:49:42Z"
  hostIP: 192.168.10.60
  phase: Running
  podIP: 10.100.1.10
  podIPs:
  - ip: 10.100.1.10
  qosClass: BestEffort
  startTime: "2024-04-26T01:49:30Z"
