apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-05-10T04:38:18Z"
  generateName: fission-fission-all-v1.20.0-818-
  labels:
    app: fission-all
    controller-uid: 369b0606-6af6-42b5-b828-b910a524eb45
    job-name: fission-fission-all-v1.20.0-818
    release: fission
  name: fission-fission-all-v1.20.0-818-2xk6g
  namespace: fission
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: fission-fission-all-v1.20.0-818
    uid: 369b0606-6af6-42b5-b828-b910a524eb45
  resourceVersion: "3542683"
  uid: 9e5ca3a8-56b6-4e1e-866b-efcb86122bee
spec:
  containers:
  - command:
    - /pre-upgrade-checks
    env:
    - name: FISSION_BUILDER_NAMESPACE
    - name: FISSION_FUNCTION_NAMESPACE
    - name: FISSION_DEFAULT_NAMESPACE
      value: default
    - name: FISSION_RESOURCE_NAMESPACES
      value: default
    image: fission/pre-upgrade-checks:v1.20.0
    imagePullPolicy: IfNotPresent
    name: pre-upgrade-job
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-7644q
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: elastic-g3wcd274rwob-node-2
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: fission-preupgrade
  serviceAccountName: fission-preupgrade
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-7644q
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-05-10T04:38:18Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-05-10T04:38:38Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-05-10T04:38:38Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-05-10T04:38:18Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://0c4befffdb213734f506a48510fecbc9784dbacf058af749aedab5d5d677489c
    image: docker.io/fission/pre-upgrade-checks:v1.20.0
    imageID: docker.io/fission/pre-upgrade-checks@sha256:328d7eee1fcfbd13a98aa8a835747dbd2ee2af8ce62cefe7c61c12bbf138d165
    lastState: {}
    name: pre-upgrade-job
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://0c4befffdb213734f506a48510fecbc9784dbacf058af749aedab5d5d677489c
        exitCode: 0
        finishedAt: "2024-05-10T04:38:36Z"
        reason: Completed
        startedAt: "2024-05-10T04:38:32Z"
  hostIP: 192.168.10.25
  phase: Succeeded
  podIP: 10.100.3.54
  podIPs:
  - ip: 10.100.3.54
  qosClass: BestEffort
  startTime: "2024-05-10T04:38:18Z"
