apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-04-26T01:49:30Z"
  generateName: mqtrigger-keda-7c8b8f5ddc-
  labels:
    messagequeue: keda
    pod-template-hash: 7c8b8f5ddc
    svc: mqtrigger-keda
  name: mqtrigger-keda-7c8b8f5ddc-xbgzs
  namespace: fission
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: mqtrigger-keda-7c8b8f5ddc
    uid: 8c151f80-c70b-4356-9529-5e1e9c9f049a
  resourceVersion: "111173"
  uid: ce82241b-eef6-40e1-875f-c519768e87e0
spec:
  containers:
  - args:
    - --mqt_keda
    - --routerUrl
    - http://router.fission
    command:
    - /fission-bundle
    env:
    - name: DEBUG_ENV
      value: "false"
    - name: CONNECTOR_IMAGE_PULL_POLICY
      value: IfNotPresent
    - name: KAFKA_IMAGE
      value: ghcr.io/fission/keda-kafka-http-connector:v0.13
    - name: RABBITMQ_IMAGE
      value: ghcr.io/fission/keda-rabbitmq-http-connector:v0.11
    - name: AWS-KINESIS-STREAM_IMAGE
      value: ghcr.io/fission/keda-aws-kinesis-http-connector:v0.11
    - name: AWS-SQS-QUEUE_IMAGE
      value: ghcr.io/fission/keda-aws-sqs-http-connector:v0.12
    - name: STAN_IMAGE
      value: ghcr.io/fission/keda-nats-streaming-http-connector:v0.14
    - name: NATS-JETSTREAM_IMAGE
      value: ghcr.io/fission/keda-nats-jetstream-http-connector:v0.5
    - name: GCP-PUBSUB_IMAGE
      value: ghcr.io/fission/keda-gcp-pubsub-http-connector:v0.7
    - name: REDIS_IMAGE
      value: ghcr.io/fission/keda-redis-http-connector:v0.4
    - name: FISSION_BUILDER_NAMESPACE
    - name: FISSION_FUNCTION_NAMESPACE
    - name: FISSION_DEFAULT_NAMESPACE
      value: default
    - name: FISSION_RESOURCE_NAMESPACES
      value: default
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
    - name: OTEL_EXPORTER_OTLP_INSECURE
      value: "true"
    - name: OTEL_TRACES_SAMPLER
      value: parentbased_traceidratio
    - name: OTEL_TRACES_SAMPLER_ARG
      value: "0.1"
    - name: OTEL_PROPAGATORS
      value: tracecontext,baggage
    image: ghcr.io/fission/fission-bundle:v1.20.0
    imagePullPolicy: IfNotPresent
    name: mqtrigger-keda
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-fg9j5
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: elastic-g3wcd274rwob-node-0
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: fission-keda
  serviceAccountName: fission-keda
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-fg9j5
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-04-26T01:49:30Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-04-26T01:49:42Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-04-26T01:49:42Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-04-26T01:49:30Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://8b03b878e96c1e10661a28b376228a61a8d98c13348df486094454750c73650a
    image: ghcr.io/fission/fission-bundle:v1.20.0
    imageID: ghcr.io/fission/fission-bundle@sha256:53bfa3f9c7ea3beb3c51775372a1ab5aa43e58a88c6fde155d0cf58663cc82bd
    lastState: {}
    name: mqtrigger-keda
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-04-26T01:49:42Z"
  hostIP: 192.168.10.60
  phase: Running
  podIP: 10.100.1.8
  podIPs:
  - ip: 10.100.1.8
  qosClass: BestEffort
  startTime: "2024-04-26T01:49:30Z"
